ENV_VARS = {
    'ENABLE_AMDIN_ACCESS': 'TIAME_ADMIN',
    'DB': {
        'HOST': 'TIAME_DB_HOST',
        'NAME': 'TIAME_DB_NAME',
        'USER': 'TIAME_DB_USER',
        'PASSWORD': 'TIAME_DB_PASSWORD',
    }
}
VERSION_AFTER_MINUTES = 5
STATUS_CODES = {
    "DELETED": 0,
    "ENABLED": 1,
}
DEFAULT_THEME = 0
DEFAULT_STATUS = STATUS_CODES['ENABLED']
